version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: stellar/transfer-server-validator
    docker:
      - image: circleci/node:latest
jobs:
  publish-build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $IMAGE_NAME:latest .
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  deploy-sep24:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $CIRCLE_BRANCH:master
  deploy-sep6:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DIRECT_PAYMENT_APP_NAME.git $CIRCLE_BRANCH:master
workflows:
  version: 2
  publish-build-deploy:
    jobs:
      - publish-build:
          filters:
            branches:
              only: master
      - deploy-sep6:
          requires:
            - publish-build
          filters:
            branches:
              only: master
      - deploy-sep24:
          requires:
            - publish-build
          filters:
            branches:
              only: master
